#!/bin/bash -e

pulp build -I test
node --input-type=module -e 'import { main } from "./output/Test.Main/index.js"; main();' > test/actual_output.txt 2>&1
diff -u test/expected_output.txt test/actual_output.txt
